version: '3.4'

services:
  registry_npm:
    build:
      context: ./
      dockerfile: ./dockerfile
    restart: always
    image: registry_npm
    container_name: registry_npm
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - 4873:4873
    volumes:
      - registry_npm_storage:/verdaccio/storage

volumes:
  registry_npm_storage:

